### ISSUE TITLE
Github actions show that `crashCommitIndex` and `byzCommitIndex` do not reach interesting values

### ISSUE THREAD

**Issue by lemmy** [PirateshipOrg/pirateship-tla#4]
https://github.com/heidihoward/pirateship-tla/actions/runs/11695920887

**Comment by heidihoward** [comment]
The max byzantine commit for all replicas is the maximum number of txns - 2 and the max crash commit for all replicas is the maximum number of txns - 1 so should be fixed by setting Tx s == 1..4
