### ISSUE TITLE
Commit Rule Not Generalisable 

### ISSUE THREAD

**Issue by nacrooks** [PirateshipOrg/pirateship-tla#9]
Line 190 of the spec says:
```
\* replica updates is commit indexes
    /\ crashCommitIndex' = [crashCommitIndex EXCEPT ![r] = Max2(@, HighestQC(log'[r]))]

```

This is correct under the assumption that N = 4 (so supermajority and majority are the same) *and* that there are no signatures (so messages are implicitly all signed). 

When we start adding signatures *and* considering quorums of different sizes, we will need a different commit rule. To crash commit, we cannot rely on the latest highest QC, but instead have to include the latest commit index from the leader (which has to be included as part of the AppendEntry), and use that to decide when to crash commit. The Byz commit rule stays unchanged.

**Comment by heidihoward** [comment]
All messages are implicitly signed. I believe that is safe (even when n # 4) as the crash commit quorum will always be smaller (or equal to) than the byzantine commit quorum but I'll change it anyways to align with the implementation

**Comment by heidihoward** [comment]
Fixed
